*introduction*

Explore the data first

In [1]:
#import the libraries
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import glob
import os

The dataset contains measurements from accelerometer,  the dataset itself is split into four different movement types:

* idle (motionless)
* running
* stairs
* walking

Aggregate datasets for convinience purposes

In [2]:
#aggregate idles
files = glob.glob(r"C:\Users\dparh\Documents\GitHub\goit-algo-hw-8\data\idle\*.csv")  # files in the directory
output_path = "idle_combined.csv"

with open(output_path, "w", encoding='utf-8') as out_file:
    for i, file_name in enumerate(files):
        if os.path.abspath(file_name) == os.path.abspath(output_path):
            continue
        with open(file_name, 'r', encoding='utf-8') as infile:
            if i == 0:
                out_file.write(infile.read())
            else:
                next(infile)
                out_file.write(infile.read())

In [3]:
#aggregate running
files = glob.glob(r"C:\Users\dparh\Documents\GitHub\goit-algo-hw-8\data\running\*.csv")  # files in the directory
output_path = "running_combined.csv"

with open(output_path, "w", encoding='utf-8') as out_file:
    for i, file_name in enumerate(files):
        if os.path.abspath(file_name) == os.path.abspath(output_path):
            continue
        with open(file_name, 'r', encoding='utf-8') as infile:
            if i == 0:
                out_file.write(infile.read())
            else:
                next(infile)
                out_file.write(infile.read())

In [4]:
#aggregate stairs
files = glob.glob(r"C:\Users\dparh\Documents\GitHub\goit-algo-hw-8\data\stairs\*.csv")  # files in the directory
output_path = "stairs_combined.csv"

with open(output_path, "w", encoding='utf-8') as out_file:
    for i, file_name in enumerate(files):
        if os.path.abspath(file_name) == os.path.abspath(output_path):
            continue
        with open(file_name, 'r', encoding='utf-8') as infile:
            if i == 0:
                out_file.write(infile.read())
            else:
                next(infile)
                out_file.write(infile.read())

In [5]:
#aggregate walking
files = glob.glob(r"C:\Users\dparh\Documents\GitHub\goit-algo-hw-8\data\walking\*.csv")  # files in the directory
output_path = "walking_combined.csv"

with open(output_path, "w", encoding='utf-8') as out_file:
    for i, file_name in enumerate(files):
        if os.path.abspath(file_name) == os.path.abspath(output_path):
            continue
        with open(file_name, 'r', encoding='utf-8') as infile:
            if i == 0:
                out_file.write(infile.read())
            else:
                next(infile)
                out_file.write(infile.read())

In [6]:
#add "activity" column to each dataset
idle = pd.read_csv("idle_combined.csv")
idle['activity'] = "idle"

idle.to_csv("idle_combined.csv")

In [7]:
walking = pd.read_csv('walking_combined.csv')
walking['activity'] = 'walking'

walking.to_csv("walking_combined.csv")

In [8]:
running = pd.read_csv('running_combined.csv')
running['activity'] = 'running'

running.to_csv("running_combined.csv")

In [9]:
stairs = pd.read_csv('stairs_combined.csv')
stairs['activity'] = 'stairs'

stairs.to_csv("stairs_combined.csv")

In [10]:
df = pd.concat([idle, running, stairs, walking], ignore_index=True)

df.to_csv("accelerometer_dateset.csv")

In [ ]:
df

        accelerometer_X  accelerometer_Y  accelerometer_Z activity
0              0.411803         6.229713         7.302315     idle
1             -0.402226         7.158664         6.469133     idle
2              0.488417         6.502652         7.709330     idle
3              0.210690         6.947974         6.574478     idle
4              0.095768         6.330270         6.943185     idle
...                 ...              ...              ...      ...
178375         5.109226       -15.452178        -1.470040  walking
178376         6.373365       -11.741165        -8.226476  walking
178377         3.289633        -9.993398        -0.383072  walking
178378        -2.978387        -3.050213         1.273715  walking
178379        -4.347870        -9.926360        -1.642422  walking

[178380 rows x 4 columns]

#### Determine the time domain features for each motion state

In [21]:
#extract features from df
#normalize data
axes = ['accelerometer_X', 'accelerometer_Y','accelerometer_Z']
df[axes] = (df[axes] - df[axes].mean() / df[axes].std())

print(df[axes])

        accelerometer_X  accelerometer_Y  accelerometer_Z
0              0.174361         6.105996         7.139301
1             -0.639668         7.034947         6.306119
2              0.250975         6.378935         7.546316
3             -0.026752         6.824257         6.411464
4             -0.141674         6.206553         6.780171
...                 ...              ...              ...
178375         4.871784       -15.575895        -1.633054
178376         6.135923       -11.864882        -8.389490
178377         3.052191       -10.117115        -0.546086
178378        -3.215829        -3.173930         1.110701
178379        -4.585312       -10.050077        -1.805436

[178380 rows x 3 columns]

In [ ]:
#windowing parameters
windows_size = 200
step_size = 100
features = []

#extract features
for i in range(0, len(df) - windows_size, step_size):
    window = df.iloc[i: i + windows_size]

    activity = window['activity'].mode()
    win_features = {'activity': activity}

    for axis in axes:
        win_features[f'{axis}_mean'] = window[axis].mean()
        win_features[f'{axis}_std'] = window[axis].std()
        win_features[f'{axis}_range'] = window[axis].max() - window[axis].min()
        win_features[f'{axis}_rms'] = np.sqrt(np.mean(window[axis]**2))
    
    win_features['SMA'] = (window[axes].abs().sum(axis=1).mean())

    features.append(win_features)
    
#create a separate dataframe for features
features_df = pd.DataFrame(features)
features_df

,activity,accelerometer_X_mean,accelerometer_X_std,accelerometer_X_range,accelerometer_X_rms,accelerometer_Y_mean,accelerometer_Y_std,accelerometer_Y_range,accelerometer_Y_rms,accelerometer_Z_mean,accelerometer_Z_std,accelerometer_Z_range,accelerometer_Z_rms,SMA
0,"0 idle Name: activity, dtype: str",0.117546,0.859106,6.033388,0.864980,2.742980,3.069466,9.097967,4.110773,8.504020,1.390885,5.913678,8.616452,11.986486
1,"0 idle Name: activity, dtype: str",0.271086,0.808576,4.146757,0.850890,1.838068,2.893685,8.159440,3.421994,8.871003,1.303970,5.832275,8.965854,11.460452
2,"0 idle Name: activity, dtype: str",0.169812,0.668334,4.146757,0.687949,0.562126,2.074653,8.082826,2.144446,9.338423,0.929590,5.832275,9.384347,10.625376
3,"0 idle Name: activity, dtype: str",-0.007551,0.509197,6.033388,0.507979,-0.086775,0.926049,9.021353,0.927798,9.544756,0.509426,5.913678,9.558273,10.128453
4,"0 idle Name: activity, dtype: str",-0.032043,0.326154,3.912125,0.326912,-0.224753,0.199370,2.049437,0.300106,9.573845,0.312843,4.548983,9.578929,9.950607
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1777,"0 walking Name: activity, dtype: str",-2.415950,3.600685,29.348123,4.328616,-9.780610,4.520267,25.354596,10.769911,-1.629439,5.733613,43.660664,5.946849,17.091416
1778,"0 walking Name: activity, dtype: str",-2.109444,3.140986,22.136788,3.777065,-10.063054,4.170175,18.267758,10.888915,-1.991658,5.246210,38.144422,5.599268,16.712463
1779,"0 walking Name: activity, dtype: str",-2.040156,3.221954,18.871097,3.806746,-10.058769,4.303385,25.354596,10.936423,-1.962089,5.455752,43.660664,5.784998,16.837018
1780,"0 walking Name: activity, dtype: str",-1.567900,3.506021,21.351490,3.832627,-10.571391,4.904965,30.415938,11.648721,-1.580406,6.349147,52.677226,6.527464,17.647705
1781,"0 walking Name: activity, dtype: str",-0.358277,3.489334,14.551958,3.498991,-10.997391,5.104444,25.383325,12.118898,-0.886183,7.604012,52.658072,7.636571,18.233048